import 'package:flutter/material.dart';
import 'package:hexcolor/hexcolor.dart';

List<Color> colorlist = [
  HexColor("7D1414"),
  Colors.purple,
  Colors.deepOrange,
  HexColor("7D1414"),
  Colors.purple,
  Colors.deepOrange,
  HexColor("7D1414"),
  Colors.purple,
  Colors.deepOrange,
  HexColor("7D1414"),
  Colors.purple,
  Colors.deepOrange,
  HexColor("7D1414"),
  Colors.purple,
  Colors.deepOrange,
  HexColor("7D1414"),
  Colors.purple,
  Colors.deepOrange,
  HexColor("7D1414"),
  Colors.purple,
  Colors.deepOrange,
  HexColor("7D1414"),
  Colors.purple,
  Colors.deepOrange,
  HexColor("7D1414"),
  Colors.purple,
  Colors.deepOrange,
  HexColor("7D1414"),
  Colors.purple,
  Colors.deepOrange,
  HexColor("7D1414"),
  Colors.purple,
  Colors.deepOrange,
  HexColor("7D1414"),
  Colors.purple,
  Colors.deepOrange,
  HexColor("7D1414"),
];

var maincolor = colorlist[0];
